[package]
name = "IWARN"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.x86_64-pc-windows-msvc]

[dependencies]

[[bin]]
name = "IWARN"
path = "IWARN.rs"
